/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EIP712Mock__factory } from "./EIP712Mock__factory";
export { EIP712Test__factory } from "./EIP712Test__factory";
