/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  ChildPotatoMigrator,
  ChildPotatoMigratorInterface,
} from "../../../../contracts/test/PotatoMigration/ChildPotatoMigrator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "potato_",
        type: "address",
      },
      {
        internalType: "address",
        name: "farm_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onStateReceive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102713803806102718339818101604052604081101561003357600080fd5b508051602090910151600080546001600160a01b039384166001600160a01b031991821617909155600180549390921692169190911790556101f78061007a6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806326c53bea14610030575b600080fd5b6100a76004803603604081101561004657600080fd5b8135919081019060408101602082013564010000000081111561006857600080fd5b82018360208201111561007a57600080fd5b8035906020019184600183028401116401000000008311171561009c57600080fd5b5090925090506100a9565b005b600080838360408110156100bc57600080fd5b50600080546001546040805163095ea7b360e01b81526001600160a01b039283166004820152602080870135602483018190529251963584169850919650929091169363095ea7b3936044808501948390030190829087803b15801561012157600080fd5b505af1158015610135573d6000803e3d6000fd5b505050506040513d602081101561014b57600080fd5b50506001546040805163181fe92f60e11b81526001600160a01b038581166004830152602482018590529151919092169163303fd25e91604480830192600092919082900301818387803b1580156101a257600080fd5b505af11580156101b6573d6000803e3d6000fd5b50505050505050505056fea2646970667358221220886d2036e6d5c8cf724dbfa47c2efd8ef71ca4a3994f8f3b71fb6c5cbd6c536a64736f6c63430006060033";

type ChildPotatoMigratorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ChildPotatoMigratorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ChildPotatoMigrator__factory extends ContractFactory {
  constructor(...args: ChildPotatoMigratorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    potato_: PromiseOrValue<string>,
    farm_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ChildPotatoMigrator> {
    return super.deploy(
      potato_,
      farm_,
      overrides || {}
    ) as Promise<ChildPotatoMigrator>;
  }
  override getDeployTransaction(
    potato_: PromiseOrValue<string>,
    farm_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(potato_, farm_, overrides || {});
  }
  override attach(address: string): ChildPotatoMigrator {
    return super.attach(address) as ChildPotatoMigrator;
  }
  override connect(signer: Signer): ChildPotatoMigrator__factory {
    return super.connect(signer) as ChildPotatoMigrator__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChildPotatoMigratorInterface {
    return new utils.Interface(_abi) as ChildPotatoMigratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChildPotatoMigrator {
    return new Contract(address, _abi, signerOrProvider) as ChildPotatoMigrator;
  }
}
