/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IChildChainManagerInterface extends utils.Interface {
  functions: {
    "cleanMapToken(address,address)": FunctionFragment;
    "mapToken(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "cleanMapToken" | "mapToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cleanMapToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "mapToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "cleanMapToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mapToken", data: BytesLike): Result;

  events: {
    "TokenMapped(address,address)": EventFragment;
    "TokenUnmapped(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokenMapped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenUnmapped"): EventFragment;
}

export interface TokenMappedEventObject {
  rootToken: string;
  childToken: string;
}
export type TokenMappedEvent = TypedEvent<
  [string, string],
  TokenMappedEventObject
>;

export type TokenMappedEventFilter = TypedEventFilter<TokenMappedEvent>;

export interface TokenUnmappedEventObject {
  rootToken: string;
  childToken: string;
}
export type TokenUnmappedEvent = TypedEvent<
  [string, string],
  TokenUnmappedEventObject
>;

export type TokenUnmappedEventFilter = TypedEventFilter<TokenUnmappedEvent>;

export interface IChildChainManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IChildChainManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cleanMapToken(
      rootToken: PromiseOrValue<string>,
      childToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mapToken(
      rootToken: PromiseOrValue<string>,
      childToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  cleanMapToken(
    rootToken: PromiseOrValue<string>,
    childToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mapToken(
    rootToken: PromiseOrValue<string>,
    childToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cleanMapToken(
      rootToken: PromiseOrValue<string>,
      childToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    mapToken(
      rootToken: PromiseOrValue<string>,
      childToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "TokenMapped(address,address)"(
      rootToken?: PromiseOrValue<string> | null,
      childToken?: PromiseOrValue<string> | null
    ): TokenMappedEventFilter;
    TokenMapped(
      rootToken?: PromiseOrValue<string> | null,
      childToken?: PromiseOrValue<string> | null
    ): TokenMappedEventFilter;

    "TokenUnmapped(address,address)"(
      rootToken?: PromiseOrValue<string> | null,
      childToken?: PromiseOrValue<string> | null
    ): TokenUnmappedEventFilter;
    TokenUnmapped(
      rootToken?: PromiseOrValue<string> | null,
      childToken?: PromiseOrValue<string> | null
    ): TokenUnmappedEventFilter;
  };

  estimateGas: {
    cleanMapToken(
      rootToken: PromiseOrValue<string>,
      childToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mapToken(
      rootToken: PromiseOrValue<string>,
      childToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cleanMapToken(
      rootToken: PromiseOrValue<string>,
      childToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mapToken(
      rootToken: PromiseOrValue<string>,
      childToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
