/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStateReceiver__factory } from "./IStateReceiver__factory";
export { MockStateSender__factory } from "./MockStateSender__factory";
