/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DummyImplementation } from "./DummyImplementation";
export type { UpgradableProxyTest } from "./UpgradableProxyTest";
