/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMurkyPredeploy } from "./IMurkyPredeploy";
export type { MurkyPredeployer } from "./MurkyPredeployer";
