#!/usr/bin/env bash
set -euo pipefail

# Run from repo root regardless of invocation directory.
cd "$(dirname "$0")/../.."

# Sanity check: forge and cast must be on PATH.
for tool in forge cast; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: '$tool' not found in PATH. Install Foundry: https://book.getfoundry.sh/getting-started/installation" >&2
    exit 1
  fi
done

# Start from a clean build so the artifact set is deterministic — otherwise
# cached test/script artifacts from a previous `forge build` would leak in
# and we'd generate interfaces for test helpers too.
forge clean

# Compile only source contracts. forge/ and scripts/ depend on the interfaces
# we're about to generate, so they must be skipped on this pass.
forge compile --skip test --skip script

# Start from a clean output dir so deleted/renamed contracts don't leave
# stale .generated.sol files behind.
rm -rf scripts/helpers/interfaces
mkdir -p scripts/helpers/interfaces

# Process one forge artifact: emit a Solidity interface stub via
# `cast interface`. Skips contracts without an ABI (libraries with no
# externals) and empty stubs (`interface Foo {}` — nothing to expose).
process_artifact() {
  local file="$1"
  local contract
  contract="$(basename "$file" .json)"
  local iface
  if ! iface=$(cast interface "$file" -n "$contract" 2>/dev/null); then
    return 0
  fi
  if printf '%s' "$iface" | grep -qE "interface ${contract} \{\}[[:space:]]*\$"; then
    return 0
  fi
  {
    printf '// Auto-generated by scripts/helpers/generateInterfaces.sh — do not edit by hand.\n'
    printf '%s\n' "$iface"
  } > "scripts/helpers/interfaces/${contract}.generated.sol"
}
export -f process_artifact

# Sort the artifact list and dedupe by contract name — two .sol files can
# declare the same contract, and without dedup the parallel writers would
# race for the output path. Lexically-first artifact wins.
find out -type f -name "*.json" \
  -not -path "*/build-info/*" \
  -not -path "*.generated*" \
  | sort \
  | awk -F/ '{name=$NF; sub(/\.json$/,"",name); if (!seen[name]++) print; else print "warning: skipping duplicate contract name "name" at "$0 > "/dev/stderr"}' \
  | tr '\n' '\0' \
  | xargs -0 -P 8 -I {} bash -c 'process_artifact "$@"' _ {}

generated=$(find scripts/helpers/interfaces -type f -name "*.generated.sol" | wc -l | tr -d ' ')
echo "Generated $generated interfaces"
