/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERCProxy } from "./IERCProxy";
export type { Proxy } from "./Proxy";
export type { UpgradableProxy } from "./UpgradableProxy";
