/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20__factory } from "./ERC20__factory";
export { UChildEIP3009__factory } from "./UChildEIP3009__factory";
export { UChildERC20__factory } from "./UChildERC20__factory";
export { UChildERC20Proxy__factory } from "./UChildERC20Proxy__factory";
