/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChildPotatoFarm } from "./ChildPotatoFarm";
export type { ChildPotatoMigrator } from "./ChildPotatoMigrator";
export type { ChildPotatoToken } from "./ChildPotatoToken";
export type { RootPotatoMigrator } from "./RootPotatoMigrator";
export type { RootPotatoToken } from "./RootPotatoToken";
