/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Mock__factory } from "./ERC20Mock__factory";
export { ERC20Test__factory } from "./ERC20Test__factory";
