/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStateReceiver } from "./IStateReceiver";
export type { MockStateSender } from "./MockStateSender";
