/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRootChainManager } from "./IRootChainManager";
export type { RootChainManager } from "./RootChainManager";
export type { RootChainManagerProxy } from "./RootChainManagerProxy";
export type { RootChainManagerStorage } from "./RootChainManagerStorage";
