/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERCProxy__factory } from "./IERCProxy__factory";
export { Proxy__factory } from "./Proxy__factory";
export { UpgradableProxy__factory } from "./UpgradableProxy__factory";
